INSERT INTO description VALUES
('0',' Latte with delicious Dark Chocolate and cream'),
('1',' Showered in unique tase of Cinamon and love'),
('2',' Classic choice of Latte'),
('3',' Perfect drinks for cold day'),
('4',' Want to impress your colleague with style? This is your pick'),
('5',' Simple but balanced'),
('6',' Our signature drink'),
('7',' Submerge yourself in the nature'),
('8',' a good way to become an Italian'),
('31',' Love is in the air'),
('32',' Classic choice'),
('33',' Never fail to impress'),
('34',' Wild and untammed'),
('35',' What you seek in a mocha is here'),
('36',' Perfect blend between passion and love'),
('37',' Soothing to the very last sip'),
('38',' Overflowing with passion '),
('39',' Straight from the future'),
('40',' One Two Three and you will never forget it'),
('61',' Love is in the air'),
('62',' Classic choice'),
('63',' Never fail to impress'),
('64',' Wild and untammed'),
('65',' What you seek in a mocha is here'),
('66',' Perfect blend between passion and love'),
('67',' Soothing to the very last sip'),
('68',' Overflowing with passion '),
('91', 'Made with Strawberry'),
('92', 'Made with Kiwi'),
('93', 'Made with Blueberry'),
('94', 'Made with Mango'),
('95', 'Made with Pineapple'),
('96', 'Made with Banana'),
('121', 'Straight out from Moon'),
('122', 'Straight out from Jupiter'),
('123', 'Straight out from Mars'),
('124', 'Straight out from Nepture'),
('125', 'Straight out from Mercury'),
('151','The taste you will never forget'),
('152','The taste you will hate to forget');
